name: Publish to PyPI

on:
  release:
    types: [ published ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: 📂 Check-Out Repository
        uses: actions/checkout@v7
      - name: 🐍 Set Up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: "pip"
          cache-dependency-path: "pyproject.toml"
      - name: ⏬ Install Required Packages
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install build
      - name: 🔨 Build Module
        run: python -m build
      - name: ⏫ Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
